// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/nanlan/Documents/my-project/umi-simple-app/node_modules/.pnpm/registry.npmjs.org+@umijs+renderer-react@4.0.79_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/nanlan/Documents/my-project/umi-simple-app/node_modules/.pnpm/registry.npmjs.org+@umijs+renderer-react@4.0.79_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/nanlan/Documents/my-project/umi-simple-app/node_modules/.pnpm/registry.npmjs.org+umi@4.0.79_@babel+core@7.22.11_@types+react@18.2.21_eslint@8.48.0_postcss@_wauixqtnah4nmmd33cpfj3z6ey/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
// plugins types.d.ts
